/* autogenerated by Processing revision 1272 on 2022-01-04 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class about extends PApplet {

PGraphics front; //fungiert als Maske
PImage backgroundImage;

 public void setup() {
  /* size commented out by preprocessor */;
  background(0);
  backgroundImage = loadImage("Web-2560x1440-150dpi_DB0196.png");
  front = createGraphics(width, height);
  colorMode(HSB);
}

 public void draw() {
  front.beginDraw();
  front.stroke(255); //wird mit 200 verschwommener, Farbe ist nie ersichtlich, bei 10 zu sehr manipuliert
  front.strokeWeight(70);
  front.line(pmouseX,pmouseY,mouseX,mouseY);
  front.endDraw();
  backgroundImage.mask(front);
  image(backgroundImage,0,0); 
  if(mouseButton == LEFT){
    background(random(0,255),255,255);
    front = createGraphics(width, height);
  }
}


  public void settings() { size(2560, 1440); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "about" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
